{
 "title": "Homelab RED",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(http_server_duration_milliseconds_count{\n      job=\"otel-collector\",\n      exported_job=\"otel-homelab-api\",\n      http_target!=\"/health\"\n    }[2m])\n  )\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\n  (\n    sum(\n      rate(http_server_duration_milliseconds_count{\n        job=\"otel-collector\",\n        exported_job=\"otel-homelab-api\",\n        http_target!=\"/health\",\n        http_status_code=~\"5..\"\n      }[2m])\n    )\n    or\n    0 * sum(\n      rate(http_server_duration_milliseconds_count{\n        job=\"otel-collector\",\n        exported_job=\"otel-homelab-api\",\n        http_target!=\"/health\"\n      }[2m])\n    )\n  )\n  /\n  sum(\n    rate(http_server_duration_milliseconds_count{\n      job=\"otel-collector\",\n      exported_job=\"otel-homelab-api\",\n      http_target!=\"/health\"\n    }[2m])\n  )\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "  histogram_quantile(\n    0.95,\n    sum by (le) (\n      rate(http_server_duration_milliseconds_bucket{\n        job=\"otel-collector\",\n        exported_job=\"otel-homelab-api\",\n        http_target!=\"/health\"\n      }[2m])\n    )\n  )\n\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}